name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for bringing this to our attention, If approved it will be turned into a pull request for a vote!' first issue"
        pr-message: "Thanks! We will will review and vote on this proposed change.' first pull request"
